spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://localhost:9898/    #spring.zipkin.base-url指定了Zipkin服务器的地址
  sleuth:
    sampler:
      probability: 1.0  # spring.sleuth.sampler.probability将采样比例设置为1.0，也就是全部都需要。

server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
