spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:9898
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080

#这里的配置表示，访问/hello/** 直接重定向到http://192.168.0.100:9001/**。即路由重定向
#zuul:
#  routes:
#    users:
#      path: /hello/**
#      url: http://192.168.0.100:9001/

# 通过服务中心提供服务
zuul:
  routes:
    users:
      path: /producer/**
      #serviceId: spring-cloud-producer   在不配置serviceId的情况下，Zuul的路由规则如下:http://zuul_host:zuul_port/微服务在Eureka上的serviceId/**  会被转发到serviceId对应的微服务。


eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8000/eureka/


# 开启Zuul Retry
#是否开启重试功能
zuul:
  retryable:  true
#对当前服务的重试次数
ribbon:
  MaxAutoRetries: 2
#切换相同Server的次数
ribbon:
  MaxAutoRetriesNextServer: 0
